# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
