# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-31 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
